// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    ExplosionCard: typeof import('./src/components/ExplosionCard.vue')['default']
    ICarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    ICarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    ICarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    ICarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    ICarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    ICarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    ICarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    IIconParkOutlineSorcererHat: typeof import('virtual:vite-icons/icon-park-outline/sorcerer-hat')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    README: typeof import('./src/components/README.md')['default']
  }
}

export { }
